### ISSUE TITLE
[Bug] Admin not able to see submitted video link

### ISSUE THREAD

**Issue by Yusuf-** [edosdigital/issues#23] opened 2023-11-27 12:55 UTC
**Describe the bug**
After the player have submitted the scores with video evidence, at the admin panel I'm not able to see the submitted video link.

**To Reproduce**
1. Go to match page
2. Click on "Submit Scores"
3. Paste link to video in the video url input field

**Expected behavior**
The admin portal should show the video link

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/7511722/120ba43e-cd91-4468-92b4-190e73f52ad0)

![image](https://github.com/edosdigital/issues/assets/7511722/fbf38270-8c7c-4f2c-8842-90475b302bb6)

![image](https://github.com/edosdigital/issues/assets/7511722/eae0e1c0-c7f4-4943-aceb-ef3cc355e99e)

## Tournament URL/ID
https://battle.dev.edosdigital.com/tournament/4z0h6xrvwscse0yvzhh6q2k4wr/1/1

**Additional context**
This bug is caused by the way the admin portal uses the submitted video link. It perceives the link to the video as an internal file.

**Comment by EJNiones** [comment] 2023-12-20 13:52
Duplicate of issue #10

**Closed by EJNiones** 2023-12-20 13:52 UTC
Labels: bug
